language: java
dist: xenial
os:
  - linux
jdk:
  - oraclejdk11
  - openjdk8
  - openjdk11
addons:
  sonarcloud:
    organization: "base-test"
    token:
      secure: $SONAR_TOKEN

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Mixermachine_base-test