language: java
dist: xenial
os:
  - linux
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
  - openjdk13
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea

addons:
  sonarcloud:
    organization: "base-test"
    token: ${SONAR_TOKEN}

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  # Only execute Sonar in one environment
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report -Dgpg.skip
  - if [[ "$(java --version)" = "openjdk 13"* ]]; then sonar-scanner; fi